# Harmony poquito gear
- type: startingGear
  id: MobPoquitoGear
  equipment:
    ears: ClothingHeadsetService
    head: ClothingHeadHatChef
    jumpsuit: ClothingUniformJumpsuitChef
    id: PoquitoIDcard

- type: startingGear
  id: WizardLichGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    head: ClothingHeadHatRedwizard
    outerClothing: ClothingOuterWizardRed
