- type: job
  id: BrigMedicHarmony
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigMedicHarmony
  setPreference: false # Makes the job not show up in the role options
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 0 # 0 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 0 # 0 hours
  startingGear: BrigMedicGearHarmony
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Medical
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BrigMedicGearHarmony
  equipment:
    id: BrigmedicPDA
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesBrigmedicHarmony
    gloves: ClothingHandsGlovesNitrile
    ears: ClothingHeadsetBrigmedic
    head: ClothingHeadHatBeretBrigmedic
    outerClothing: ClothingOuterCoatAMG
    belt: ClothingBeltBrigmedFilledHarmony
    back: ClothingBackpackBrigmedic
    pocket1: WeaponDisabler
    pocket2: ScalpelAdvanced
  storage:
    back:
    - Flash
