- type: job
  id: PermaPrisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPermaPrisoner
  startingGear: PermaPrisonerGear
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-security
  canBeAntag: false
  allowRestrictedContraband: false

- type: startingGear
  id: PermaPrisonerGear
  equipment:
    id: PrisonerPDA
    shoes: ClothingShoesColorBlack
    ears: ClothingHeadsetGrey
