# SPDX-FileCopyrightText: 2025 V <97265903+formlessnameless@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 corresp0nd <46357632+corresp0nd@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

- type: antag
  id: Recruiter
  name: roles-antag-syndicate-recruiter-name
  objective: roles-antag-syndicate-recruiter-objective
  antagonist: false # you ask questions and write papers not kill people
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # Matches LPO playtime. Reduced from original PR of 24hours to match with harmony's reduced hours.

- type: startingGear
  id: SyndicateRecruiterGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateBusinessSuitHarmony #Harmony Changes, uses our unique business suit
    back: ClothingBackpackSatchel
    head: ClothingHeadHatFedoraBrown
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingOuterCybersunOvercoat
    shoes: ClothingShoesLeather
    id: SyndiPDA
    ears: ClothingHeadsetGrey
    pocket1: PenRecruiter
    pocket2: RubberStampSyndicate
    belt: ClothingBeltSyndicateUtility
  inhand:
  - RecruiterBriefcase
