- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Marathon
  - Packed
# - Plasma # Not in Harmony rotation
  - Exo
# - Snowball # Not in Harmony rotation
# - Serpentcrest # Not In Harmony rotation
  - Sushi
  - Tram2
  # Harmony maps start
  - Aspid
  - Atlas
  - Barratry
  - Elkridge
  - Jellyfish
  - Mira
  - Omega
  - Prime
  - Scylla
  - Wapiti
  - Amber
  - Dove
  # Harmony maps end
