- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Elkridge
  - Fland
  - Marathon
  - Oasis
  - Packed
  - Plasma
  - Reach
  # Harmony change - Derotates Exo
  # - Exo
  # Harmony maps start
  - Aspid
  - Barratry
  - Atlas
  - Mira
  - Prime
  - Omega
  # Harmony maps end
