using Content.Shared._Harmony.ReadyManifest;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Harmony.ReadyManifest.UI;

[GenerateTypedNameReferences]
public sealed partial class ReadyManifestJobListing : GridContainer
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public ReadyManifestJobListing(ProtoId<JobPrototype> jobId, ReadyManifestJobData? readyCount)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var spriteSystem = _entityManager.System<SpriteSystem>();

        if (!_prototypeManager.TryIndex(jobId, out var job))
            return;

        if (_prototypeManager.TryIndex(job.Icon, out var icon))
            JobIcon.Texture = spriteSystem.Frame0(icon.Icon);
        else
            JobDataHolder.RemoveChild(JobIcon);

        JobTitle.Text = Loc.GetString("ready-manifest-job-title", ("jobTitle", job.LocalizedName));

        // If we don't have a ready count, assume no one is ready.
        if (readyCount == null)
        {
            ReadyCount.Text = Loc.GetString("ready-manifest-no-ready-count");
            return;
        }

        // Show the appropriate ready count text depending on the amount of people ready for the role in this order:
        // - If the number of high readies is higher than 0, show that
        // - If the number of medium readies is higher than 0, show that
        // - If the number of low readies is higher than 0, show that
        // - If nobody is ready, show that
        if (readyCount.Value.HighReadies > 0)
            ReadyCount.Text = Loc.GetString("ready-manifest-high-ready-count", ("count", readyCount.Value.HighReadies));
        else if (readyCount.Value.MediumReadies > 0)
            ReadyCount.Text = Loc.GetString("ready-manifest-medium-ready-count", ("count", readyCount.Value.MediumReadies));
        else if (readyCount.Value.LowReadies > 0)
            ReadyCount.Text = Loc.GetString("ready-manifest-low-ready-count", ("count", readyCount.Value.LowReadies));
        else
            ReadyCount.Text = Loc.GetString("ready-manifest-no-ready-count");
    }
}
