- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBloodBrother
  name: Blood Brother Role
  components:
  - type: BloodBrotherRole
  - type: MindRole
    antagPrototype: BloodBrother
    exclusiveAntag: true
    roleType: TeamAntagonist
    subtype: role-subtype-blood-brother

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleInstigator
  name: Marauder Role
  components:
  - type: TraitorRole
  - type: MindRole
    antagPrototype: Instigator
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-instigator
