- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleBloodBrother
  name: Blood Brother Role
  components:
  - type: BloodBrotherRole
  - type: MindRole
    antagPrototype: BloodBrother
    exclusiveAntag: true
    roleType: TeamAntagonist
    subtype: role-subtype-blood-brother

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleMalfunctioningAI
  name: MalfunctioningAIRole
  components:
  - type: MindRole
    roleType: TeamAntagonist
    exclusiveAntag: true
    antagPrototype: MalfunctioningAI
    subtype: role-subtype-malfunctioning-ai
  - type: MalfunctioningAIRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleMalfunctioningCyborg
  name: MalfunctioningCyborgRole
  components:
  - type: MindRole
    roleType: TeamAntagonist
    exclusiveAntag: true
    antagPrototype: MalfunctioningCyborg
    subtype: role-subtype-malfunctioning-cyborg
  - type: MalfunctioningCyborgRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleConspirator
  name: Conspirator Role
  components:
  - type: ConspiratorRole
  - type: MindRole
    antagPrototype: Conspirator
    exclusiveAntag: true
    roleType: TeamAntagonist
    subtype: role-subtype-conspirator
