- type: entity
  parent: BaseMindRoleAntag
  id: MindRolePostOperator
  name: Listening Post Role
#  description: mind-role-post-op-description
  components:
  - type: MindRole
    antagPrototype: ListeningPost
    exclusiveAntag: true
    roleType: TeamAntagonist
  - type: ListeningPostRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleHitman
  name: Hitman
  components:
  - type: MindRole
    subtype: role-subtype-hitman
    antagPrototype: Hitman
    exclusiveAntag: true
  - type: HitmanRole
  - type: RoleBriefing
    briefing: hitman-briefing
