using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Content.Shared.Mind;
using Content.Client.Silicons.Laws.SiliconLawEditUi;

namespace Content.Client._Harmony.Objectives;

[GenerateTypedNameReferences]
public sealed partial class ManageObjectivesUi : FancyWindow
{
    public readonly EntityManager _entityManager = default!;
    public ManageObjectivesUi()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(EntityUid mind)
    {
        ObjectivesBox.RemoveAllChildren();
        if (!_entityManager.TryGetComponent<MindComponent>(mind, out var mindComp))
            return;

        mindComp.Objectives.ForEach(x => ObjectivesBox.AddChild(new SiliconLawContainer()));
    }
}
