using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Content.Shared.Objectives;

namespace Content.Client._Harmony.Objectives;

[GenerateTypedNameReferences]
public sealed partial class ManageObjectivesUi : FancyWindow
{
    public ManageObjectivesUi()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(List<ObjectiveContainerData> objectives)
    {
        ObjectivesBox.RemoveAllChildren();
        objectives.ForEach(x => ObjectivesBox.AddChild(new ObjectiveContainer(x)));
    }
}
