using Content.Shared.Objectives.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Harmony.Objectives;

[GenerateTypedNameReferences]
public sealed partial class ObjectiveContainer : BoxContainer
{
    private ValueTuple<string, string> _objective;
    public ObjectiveContainer(ValueTuple<string, string> objective)
    {
        RobustXamlLoader.Load(this);
        _objective = objective;

        UpdateState();
    }

    public void SetObjective(ValueTuple<string, string> objective)
    {
        _objective = objective;
    }

    private void UpdateState()
    {
        ObjectiveNameLabel.Text = _objective.Item1;
        ObjectiveContentTextEdit.TextRope = new Rope.Leaf(_objective.Item2);
    }
}
