using Content.Shared.Mind;
using Content.Shared.Objectives;
using Content.Shared.Objectives.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Harmony.Objectives;

[GenerateTypedNameReferences]
public sealed partial class ObjectiveContainer : Control
{
    private readonly EntityManager _entityManager = default!;
    private ObjectiveContainerData _objective;
    public ObjectiveContainer(ObjectiveContainerData objective)
    {
        RobustXamlLoader.Load(this);
        _entityManager = IoCManager.Resolve<EntityManager>();
        _objective = objective;

        UpdateState();
    }

    public void SetObjective(ObjectiveContainerData objective)
    {
        _objective = objective;
    }

    private void UpdateState()
    {
        ObjectiveNameLabel.Text = _objective.Name;
        ObjectiveContentTextEdit.TextRope = new Rope.Leaf(_objective.Description);
    }
}
