// SPDX-FileCopyrightText: 2026 Fruitsalad <949631+Fruitsalad@users.noreply.github.com>
// SPDX-License-Identifier: MIT

using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Shared.Atmos;
using Content.Shared.Body;
using Content.Shared.Body.Components;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.Hands.Components;
using Content.Shared.Hands.EntitySystems;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.Medical.Surgery;
using Content.Shared.Medical.Surgery.Prototypes;
using Content.Shared.MedicalScanner;
using Content.Shared.Mobs;
using Content.Shared.Mobs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
namespace Content.Client.HealthAnalyzer.UI;

// Health analyzer UI is split from its window because it's used by both the
// health analyzer item and the cryo pod UI.

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerControl : BoxContainer
{
    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;
    private readonly IPlayerManager _playerManager;

    private HealthAnalyzerUiState _state;
    private HealthAnalyzerMode _mode = HealthAnalyzerMode.Health;
    private NetEntity? _selectedBodyPart;
    private SurgeryLayer _selectedLayer = SurgeryLayer.Skin;
    private SurgeryLayerStateData? _prevLayerStateForSelectedPart;

    public Action<SurgeryRequestBuiMessage>? OnSurgeryRequest;

    public HealthAnalyzerControl()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();
        _playerManager = dependencies.Resolve<IPlayerManager>();

        HealthModeButton.ToggleMode = true;
        IntegrityModeButton.ToggleMode = true;
        SurgeryModeButton.ToggleMode = true;
        SkinLayerButton.ToggleMode = true;
        TissueLayerButton.ToggleMode = true;
        OrganLayerButton.ToggleMode = true;

        HealthModeButton.OnPressed += _ => SetMode(HealthAnalyzerMode.Health);
        IntegrityModeButton.OnPressed += _ => SetMode(HealthAnalyzerMode.Integrity);
        SurgeryModeButton.OnPressed += _ => SetMode(HealthAnalyzerMode.Surgery);
        SkinLayerButton.OnPressed += _ => SetSurgeryLayer(SurgeryLayer.Skin);
        TissueLayerButton.OnPressed += _ => SetSurgeryLayer(SurgeryLayer.Tissue);
        OrganLayerButton.OnPressed += _ => SetSurgeryLayer(SurgeryLayer.Organ);

        UpdateModeButtonStates();
    }

    private void SetMode(HealthAnalyzerMode mode)
    {
        _mode = mode;
        UpdateModeButtonStates();
        BodyHeaderContainer.Visible = _state.TargetEntity != null;
        HealthContent.Visible = mode == HealthAnalyzerMode.Health;
        GroupsContainer.Visible = mode == HealthAnalyzerMode.Health;
        HealthDivider.Visible = mode == HealthAnalyzerMode.Health;
        AlertsDivider.Visible = mode == HealthAnalyzerMode.Health && (_state.Unrevivable == true || _state.Bleeding == true);
        AlertsContainer.Visible = AlertsDivider.Visible;
        IntegrityContent.Visible = mode == HealthAnalyzerMode.Integrity;
        SurgeryContent.Visible = mode == HealthAnalyzerMode.Surgery;
        BodyDiagram.IsClickable = mode == HealthAnalyzerMode.Surgery;
        if (mode == HealthAnalyzerMode.Integrity)
            UpdateIntegrityView();
        if (mode == HealthAnalyzerMode.Surgery)
            UpdateSurgeryView();
    }

    private void SetSurgeryLayer(SurgeryLayer layer)
    {
        _selectedLayer = layer;
        UpdateSurgeryView(autoSelectDeepest: false);
    }

    private void UpdateIntegrityView()
    {
        IntegrityLabel.Text = _state.IntegrityTotal.HasValue && _state.IntegrityMax.HasValue
            ? (_state.IntegrityMax.Value - _state.IntegrityTotal.Value).ToString()
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        IntegrityPenaltiesList.RemoveAllChildren();
        var entries = _state.IntegrityPenaltyEntries;
        if (entries == null || entries.Count == 0)
        {
            var emptyLabel = new Label
            {
                Text = Loc.GetString("health-analyzer-integrity-no-penalties"),
                StyleClasses = { "LabelSubText" }
            };
            IntegrityPenaltiesList.AddChild(emptyLabel);
            return;
        }
        foreach (var entry in entries)
        {
            AddIntegrityPenaltyEntry(IntegrityPenaltiesList, entry, 0);
        }
    }

    private void AddIntegrityPenaltyEntry(BoxContainer parent, IntegrityPenaltyDisplayEntry entry, int indentLevel)
    {
        var desc = entry.Description.StartsWith("health-analyzer-") ? Loc.GetString(entry.Description) : entry.Description;
        var label = new Label
        {
            Text = $"{desc}: -{entry.Amount}",
            StyleClasses = { "LabelSubText" },
            Margin = new Thickness(indentLevel * 15, 0, 0, 0)
        };
        parent.AddChild(label);
        if (entry.Children != null)
        {
            foreach (var child in entry.Children)
            {
                AddIntegrityPenaltyEntry(parent, child, indentLevel + 1);
            }
        }
    }

    private void UpdateSurgeryView(bool autoSelectDeepest = true)
    {
        SurgeryStepsList.RemoveAllChildren();

        if (_state.TargetEntity == null || _state.BodyParts == null)
            return;

        BodyDiagram.SetTarget(_state.TargetEntity, _state.BodyPartLayerState ?? new List<SurgeryLayerStateData>());
        BodyDiagram.OnBodyPartSelected = part =>
        {
            _selectedBodyPart = part;
            BodyDiagram.SetSelectedBodyPart(part);
            SelectDeepestOpenedLayer(part);
            _prevLayerStateForSelectedPart = _state.BodyPartLayerState?.FirstOrDefault(s => s.BodyPart == part) ?? default;
            UpdateLayerButtonAccessibility();
            UpdateSurgerySteps();
        };

        if (_state.BodyParts.Count > 0 || (_state.BodyPartLayerState?.Any(s => s.BodyPart == _state.TargetEntity) ?? false))
        {
            var selectionValid = _selectedBodyPart.HasValue
                && (_state.BodyParts.Contains(_selectedBodyPart.Value) || _selectedBodyPart.Value == _state.TargetEntity);
            if (!selectionValid)
            {
                var prevCategoryId = _prevLayerStateForSelectedPart?.CategoryId;
                var matchingEntry = !string.IsNullOrEmpty(prevCategoryId) && _state.BodyPartLayerState != null
                    ? _state.BodyPartLayerState.FirstOrDefault(s => s.CategoryId == prevCategoryId)
                    : default(SurgeryLayerStateData);
                if (matchingEntry.CategoryId == prevCategoryId)
                    _selectedBodyPart = matchingEntry.BodyPart;
                else if (_state.BodyParts.Count > 0)
                    _selectedBodyPart = _state.BodyParts[0];
                else
                    _selectedBodyPart = _state.TargetEntity;
            }
        }
        else
        {
            _selectedBodyPart = null;
        }

        BodyDiagram.SetSelectedBodyPart(_selectedBodyPart);
        if (_selectedBodyPart.HasValue && autoSelectDeepest)
        {
            var layerState = _state.BodyPartLayerState?.FirstOrDefault(s => s.BodyPart == _selectedBodyPart) ?? default;
            var prev = _prevLayerStateForSelectedPart.GetValueOrDefault();
            var bodyPartChanged = !_prevLayerStateForSelectedPart.HasValue
                || prev.BodyPart != _selectedBodyPart;
            var layerJustOpened = !bodyPartChanged
                && (layerState.SkinRetracted && !prev.SkinRetracted
                    || layerState.TissueRetracted && !prev.TissueRetracted
                    || layerState.BonesSawed && !prev.BonesSawed);
            if (bodyPartChanged || layerJustOpened)
                SelectDeepestOpenedLayer(_selectedBodyPart.Value);
            _prevLayerStateForSelectedPart = layerState;
        }
        UpdateLayerButtonAccessibility();
        UpdateSurgerySteps();
    }

    private void SelectDeepestOpenedLayer(NetEntity bodyPart)
    {
        var layerState = _state.BodyPartLayerState?.FirstOrDefault(s => s.BodyPart == bodyPart) ?? default;
        _selectedLayer = GetDeepestOpenedLayer(layerState);
    }

    private static SurgeryLayer GetDeepestOpenedLayer(SurgeryLayerStateData layerState)
    {
        if (layerState.BonesSawed) return SurgeryLayer.Organ;
        if (layerState.TissueRetracted) return SurgeryLayer.Organ;
        if (layerState.SkinRetracted) return SurgeryLayer.Tissue;
        return SurgeryLayer.Skin;
    }

    private void UpdateModeButtonStates()
    {
        UpdateButtonState(HealthModeButton, _mode == HealthAnalyzerMode.Health);
        UpdateButtonState(IntegrityModeButton, _mode == HealthAnalyzerMode.Integrity);
        UpdateButtonState(SurgeryModeButton, _mode == HealthAnalyzerMode.Surgery);
    }

    private void UpdateLayerButtonAccessibility()
    {
        var isEmptySlot = _selectedBodyPart == _state.TargetEntity;
        var layerState = _selectedBodyPart.HasValue && _state.BodyPartLayerState != null
            ? _state.BodyPartLayerState.FirstOrDefault(s => s.BodyPart == _selectedBodyPart)
            : default;

        // Current layer: green, pressed, disabled (not clickable). Others: white, unpressed, disabled only if locked.
        // Empty slots: only Organ is relevant (AttachLimb); Skin/Tissue have nothing to open.
        // Non-empty: Skin never locked (backtracking). Tissue locked until skin opened; Organ until tissue opened.
        if (isEmptySlot)
        {
            UpdateButtonState(SkinLayerButton, false, true);
            UpdateButtonState(TissueLayerButton, false, true);
            UpdateButtonState(OrganLayerButton, true, false);
        }
        else
        {
            UpdateButtonState(SkinLayerButton, _selectedLayer == SurgeryLayer.Skin, false);
            UpdateButtonState(TissueLayerButton, _selectedLayer == SurgeryLayer.Tissue, !layerState.SkinRetracted);
            UpdateButtonState(OrganLayerButton, _selectedLayer == SurgeryLayer.Organ, !layerState.TissueRetracted);
        }
    }

    private static void UpdateButtonState(Button button, bool isSelected, bool isLocked = false)
    {
        if (isSelected)
        {
            button.Pressed = true;
            button.Disabled = true;
            button.Modulate = Color.LimeGreen;
        }
        else
        {
            button.Pressed = false;
            button.Disabled = isLocked;
            button.Modulate = Color.White;
        }
    }

    private void UpdateSurgerySteps()
    {
        SurgeryStepsList.RemoveAllChildren();
        if (!_selectedBodyPart.HasValue || _state.TargetEntity == null)
            return;

        var layerState = _state.BodyPartLayerState != null
            ? _state.BodyPartLayerState.FirstOrDefault(s => s.BodyPart == _selectedBodyPart)
            : default;

        var availableStepIds = layerState.AvailableStepIds ?? [];
        var orderedSkinStepIds = layerState.OrderedSkinStepIds ?? [];
        var orderedTissueStepIds = layerState.OrderedTissueStepIds ?? [];

        if (_selectedLayer == SurgeryLayer.Skin)
        {
            AddOrderedSteps(orderedSkinStepIds, availableStepIds, SurgeryLayer.Skin, layerState: layerState);
        }
        if (_selectedLayer == SurgeryLayer.Tissue)
        {
            AddOrderedSteps(orderedTissueStepIds, availableStepIds, SurgeryLayer.Tissue, layerState: layerState);
        }
        if (_selectedLayer == SurgeryLayer.Organ)
        {
            if (!layerState.OrganOpen && layerState.TissueOpen)
                AddOrderedSteps(orderedTissueStepIds, availableStepIds, SurgeryLayer.Tissue, layerState: layerState);

            if (layerState.OrganOpen)
            {
                var availableOrganSteps = layerState.AvailableOrganSteps ?? [];
                foreach (var organStep in availableOrganSteps)
                {
                    var organEntity = _entityManager.GetEntity(organStep.Organ);
                    var organName = _entityManager.TryGetComponent<MetaDataComponent>(organEntity, out var meta)
                        ? meta.EntityName
                        : Loc.GetString("health-analyzer-window-entity-unknown-text");
                    var stepName = GetProcedureDisplayName(organStep.StepId, organName);
                    AddStepButton(organStep.StepId, stepName, organStep.Organ);
                }

                var detachLimbCategories = new[] { "ArmLeft", "ArmRight", "LegLeft", "LegRight" };
                if (availableStepIds.Contains("DetachLimb") && layerState.CategoryId != null && detachLimbCategories.Contains(layerState.CategoryId))
                {
                    AddStepButton("DetachLimb", GetProcedureDisplayNameWithTool("DetachLimb"));
                }

                if (availableStepIds.Contains("InsertOrgan") || availableStepIds.Contains("AttachLimb"))
                {
                    var localPlayer = _playerManager.LocalSession?.AttachedEntity;
                    if (localPlayer.HasValue && _entityManager.TryGetComponent<HandsComponent>(localPlayer.Value, out var hands) && hands != null)
                    {
                        var handsSystem = _entityManager.System<SharedHandsSystem>();
                        // Only count limbs the body actually has; empty slots have BodyPart == TargetEntity
                        var existingLimbCategories = (_state.BodyPartLayerState ?? new List<SurgeryLayerStateData>())
                            .Where(s => s.BodyPart != _state.TargetEntity)
                            .Select(s => s.CategoryId).Where(c => c != null).ToHashSet();
                        foreach (var held in handsSystem.EnumerateHeld((localPlayer.Value, hands)))
                        {
                            if (!_entityManager.TryGetComponent(held, out OrganComponent? organComp) || organComp.Body.HasValue)
                                continue;
                            var categoryId = organComp.Category?.ToString();
                            if (categoryId == null)
                                continue;
                            if (availableStepIds.Contains("InsertOrgan") && (layerState.EmptySlots ?? []).Contains(categoryId))
                            {
                                var organName = _entityManager.TryGetComponent(held, out MetaDataComponent? heldMeta)
                                    ? heldMeta.EntityName
                                    : Loc.GetString("health-analyzer-window-entity-unknown-text");
                                AddStepButton("InsertOrgan", GetProcedureDisplayName("InsertOrgan", organName), _entityManager.GetNetEntity(held));
                            }
                            else if (availableStepIds.Contains("AttachLimb") && detachLimbCategories.Contains(categoryId) && !existingLimbCategories.Contains(categoryId))
                            {
                                AddStepButton("AttachLimb", GetProcedureDisplayNameWithTool("AttachLimb"), _entityManager.GetNetEntity(held));
                            }
                        }
                    }
                }
            }
        }

        if (SurgeryStepsList.ChildCount == 0)
        {
            var emptyLabel = new Label
            {
                Text = Loc.GetString("health-analyzer-surgery-no-steps-available"),
                StyleClasses = { "LabelSubText" }
            };
            SurgeryStepsList.AddChild(emptyLabel);
        }
    }

    /// <summary>
    /// Adds 3 paired step buttons per layer. Each button shows either the open step or its paired close step
    /// based on current state; pressing performs the step and the UI updates to show the next.
    /// </summary>
    private void AddOrderedSteps(IReadOnlyList<string> orderedStepIds, IReadOnlyList<string> availableStepIds, SurgeryLayer layer, SurgeryLayerStateData? layerState = null)
    {
        if (orderedStepIds.Count < 6)
            return;

        var availableSet = availableStepIds.ToHashSet();
        var performedSet = GetPerformedStepIds(layerState, layer).ToHashSet();

        var openStepIds = new[] { orderedStepIds[0], orderedStepIds[1], orderedStepIds[2] };
        var closeStepIds = new[] { orderedStepIds[5], orderedStepIds[4], orderedStepIds[3] };

        for (var i = 0; i < 3; i++)
        {
            var openStepId = openStepIds[i];
            var closeStepId = closeStepIds[i];
            var openPerformed = performedSet.Contains(openStepId);
            var closePerformed = performedSet.Contains(closeStepId);

            string stepId;
            bool disabled;
            if (!openPerformed)
            {
                stepId = openStepId;
                disabled = !availableSet.Contains(openStepId);
            }
            else if (!closePerformed)
            {
                stepId = closeStepId;
                disabled = !availableSet.Contains(closeStepId);
            }
            else
            {
                stepId = closeStepId;
                disabled = true;
            }

            var displayName = GetProcedureDisplayNameWithTool(stepId);
            AddStepButton(stepId, displayName, null, disabled: disabled);
        }
    }

    private static IEnumerable<string> GetPerformedStepIds(SurgeryLayerStateData? layerState, SurgeryLayer layer)
    {
        if (!layerState.HasValue)
            yield break;

        var state = layerState.Value;
        var procedures = layer switch
        {
            SurgeryLayer.Skin => state.SkinProcedures,
            SurgeryLayer.Tissue => state.TissueProcedures,
            _ => null
        };

        if (procedures == null)
            yield break;

        foreach (var p in procedures)
        {
            if (p.Performed)
                yield return p.StepId;
        }
    }

    private string GetProcedureDisplayNameWithTool(string stepId)
    {
        if (!_prototypes.TryIndex<SurgeryProcedurePrototype>(stepId, out var procedure))
            return stepId;

        if (procedure.RequiresTool == false || procedure.PrimaryTool.IsHand)
            return Loc.GetString("health-analyzer-surgery-step-no-tool", ("step", Loc.GetString(procedure.Name ?? stepId)));

        var baseName = procedure.Name != null ? Loc.GetString(procedure.Name) : stepId;
        var toolName = GetToolDisplayName(procedure.PrimaryTool);
        var improvisedName = GetImprovisedShortName(procedure, stepId);

        if (procedure.ImprovisedTools.Count == 0)
            return Loc.GetString("health-analyzer-surgery-step-primary-only", ("step", baseName), ("tool", toolName));

        return Loc.GetString("health-analyzer-surgery-step-with-tool",
            ("step", baseName),
            ("tool", toolName),
            ("improvised", improvisedName));
    }

    private string GetToolDisplayName(PrimaryToolSpec primaryTool)
    {
        if (primaryTool.IsHand)
            return "-";
        if (primaryTool.Tag.HasValue)
            return GetToolDisplayNameByTag(primaryTool.Tag.Value.ToString());
        if (primaryTool.DamageType.HasValue)
            return GetDamageTypeDisplayName(primaryTool.DamageType.Value, "CreateIncision");
        return "-";
    }

    private string GetToolDisplayNameByTag(string tagId)
    {
        foreach (var proto in _prototypes.EnumeratePrototypes<SurgicalToolPrototype>())
        {
            if (proto.Tag.ToString() == tagId || proto.ID == tagId)
                return Loc.GetString(proto.DisplayName);
        }
        return tagId;
    }

    private static string GetDamageTypeDisplayName(ImprovisedDamageType damageType, string stepId)
    {
        return damageType switch
        {
            ImprovisedDamageType.Slash => stepId is "DetachLimb" or "DetachFoot"
                ? Loc.GetString("health-analyzer-surgery-improvised-cutting")
                : Loc.GetString("health-analyzer-surgery-improvised-slash"),
            ImprovisedDamageType.Heat => Loc.GetString("health-analyzer-surgery-improvised-heat"),
            ImprovisedDamageType.Blunt => stepId is "RetractSkin" or "ReleaseRetractor" or "RetractTissue"
                ? Loc.GetString("health-analyzer-surgery-improvised-prying")
                : Loc.GetString("health-analyzer-surgery-improvised-blunt"),
            _ => "-"
        };
    }

    private string GetImprovisedShortName(SurgeryProcedurePrototype procedure, string stepId)
    {
        if (procedure.ImprovisedTools.Count == 0)
            return "-";

        var first = procedure.ImprovisedTools[0];
        if (first.DamageType.HasValue)
        {
            return GetDamageTypeDisplayName(first.DamageType.Value, stepId);
        }

        if (first.Tag.HasValue)
        {
            var tagStr = first.Tag.Value.ToString();
            return stepId == "ClampVessels" && tagStr == "Wirecutter"
                ? Loc.GetString("health-analyzer-surgery-tool-wirecutters")
                : GetToolDisplayNameByTag(tagStr);
        }
        return "-";
    }

    private string GetStepDisplayName(string stepId, SurgeryStepPrototype step, SurgeryLayerStateData? layerState)
    {
        if (step.Name == null)
            return stepId;
        return Loc.GetString(step.Name);
    }

    private string GetProcedureDisplayName(string stepId, string organName)
    {
        if (!_prototypes.TryIndex<SurgeryProcedurePrototype>(stepId, out var procedure) || procedure.Name == null)
            return stepId;

        // Feet use DetachFoot: show "Detach Foot (-/-)"
        if (stepId == "DetachFoot")
        {
            return Loc.GetString("health-analyzer-surgery-step-no-tool",
                ("step", Loc.GetString("health-analyzer-surgery-step-detach-foot")));
        }

        // RemoveOrgan, InsertOrgan, AttachLimb (when no tool): show "Remove Organ (lungs) (-/-)" etc.
        if ((stepId == "RemoveOrgan" || stepId == "InsertOrgan" || stepId == "AttachLimb") &&
            (!procedure.RequiresTool || procedure.PrimaryTool.IsHand))
        {
            var stepName = Loc.GetString(procedure.Name);
            var label = $"{stepName} ({organName})";
            return Loc.GetString("health-analyzer-surgery-step-no-tool", ("step", label));
        }

        var baseName = Loc.GetString(procedure.Name);
        var stepWithOrgan = $"{baseName} ({organName})";
        var toolName = GetToolDisplayName(procedure.PrimaryTool);
        var improvisedName = GetImprovisedShortName(procedure, stepId);

        if (procedure.ImprovisedTools.Count == 0)
            return Loc.GetString("health-analyzer-surgery-step-primary-only", ("step", stepWithOrgan), ("tool", toolName));

        return Loc.GetString("health-analyzer-surgery-step-with-tool",
            ("step", stepWithOrgan),
            ("tool", toolName),
            ("improvised", improvisedName));
    }

    private void AddStepButton(string stepId, string buttonText, NetEntity? organ = null, bool disabled = false)
    {
        var layer = _selectedLayer;
        if (_prototypes.TryIndex<SurgeryProcedurePrototype>(stepId, out var procedure))
            layer = procedure.Layer;
        else if (_prototypes.TryIndex<SurgeryStepPrototype>(stepId, out var step))
            layer = step.Layer;

        var btn = new Button
        {
            Text = buttonText,
            Disabled = disabled,
            // Use Press mode so the action fires on mouse-down. On Windows, the first click on an
            // unfocused window activates it and can consume the mouse-up; firing on mouse-down
            // ensures the procedure runs on the first click.
            Mode = BaseButton.ActionMode.Press
        };
        if (disabled)
            btn.Modulate = Color.Gray;
        btn.OnPressed += _ =>
        {
            if (disabled || _state.TargetEntity == null || !_selectedBodyPart.HasValue)
                return;
            OnSurgeryRequest?.Invoke(new SurgeryRequestBuiMessage(
                _state.TargetEntity.Value,
                _selectedBodyPart.Value,
                (ProtoId<SurgeryProcedurePrototype>)stepId,
                layer,
                false,
                organ));
        };
        SurgeryStepsList.AddChild(btn);
    }

    public void Populate(HealthAnalyzerUiState state)
    {
        _state = state;
        var target = _entityManager.GetEntity(state.TargetEntity);

        if (target == null
            || !_entityManager.TryGetComponent<DamageableComponent>(target, out var damageable))
        {
            NoPatientDataText.Visible = true;
            return;
        }

        NoPatientDataText.Visible = false;

        // Scan Mode

        ScanModeLabel.Text = state.ScanMode.HasValue
            ? state.ScanMode.Value
                ? Loc.GetString("health-analyzer-window-scan-mode-active")
                : Loc.GetString("health-analyzer-window-scan-mode-inactive")
            : Loc.GetString("health-analyzer-window-entity-unknown-text");

        ScanModeLabel.FontColorOverride = state.ScanMode.HasValue && state.ScanMode.Value ? Color.Green : Color.Red;

        // Patient Information - use BodyDiagram (standing preview) for all modes

        BodyDiagram.SetTarget(state.TargetEntity, state.BodyPartLayerState ?? new List<SurgeryLayerStateData>());
        BodyDiagram.Visible = state.ScanMode.HasValue && state.ScanMode.Value;
        NoDataTex.Visible = !BodyDiagram.Visible;

        var name = new FormattedMessage();
        name.PushColor(Color.White);
        name.AddText(_entityManager.HasComponent<MetaDataComponent>(target.Value)
            ? Identity.Name(target.Value, _entityManager)
            : Loc.GetString("health-analyzer-window-entity-unknown-text"));
        NameLabel.SetMessage(name);

        SpeciesLabel.Text =
            _entityManager.TryGetComponent<HumanoidProfileComponent>(target.Value,
                out var humanoidComponent)
                ? Loc.GetString(_prototypes.Index(humanoidComponent.Species).Name)
                : Loc.GetString("health-analyzer-window-entity-unknown-species-text");

        // Basic Diagnostic

        TemperatureLabel.Text = !float.IsNaN(state.Temperature)
            ? $"{state.Temperature - Atmospherics.T0C:F1} °C ({state.Temperature:F1} K)"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        BloodLabel.Text = !float.IsNaN(state.BloodLevel)
            ? $"{state.BloodLevel * 100:F1} %"
            : Loc.GetString("health-analyzer-window-entity-unknown-value-text");

        StatusLabel.Text =
            _entityManager.TryGetComponent<MobStateComponent>(target.Value, out var mobStateComponent)
                ? GetStatus(mobStateComponent.CurrentState)
                : Loc.GetString("health-analyzer-window-entity-unknown-text");

        // Total Damage

        DamageLabel.Text = damageable.TotalDamage.ToString();

        // Alerts

        var showAlerts = state.Unrevivable == true || state.Bleeding == true;

        AlertsDivider.Visible = showAlerts;
        AlertsContainer.Visible = showAlerts;

        if (showAlerts)
            AlertsContainer.RemoveAllChildren();

        if (state.Unrevivable == true)
            AlertsContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-unrevivable-text"),
                Margin = new Thickness(0, 4),
                MaxWidth = 300
            });

        if (state.Bleeding == true)
            AlertsContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("health-analyzer-window-entity-bleeding-text"),
                Margin = new Thickness(0, 4),
                MaxWidth = 300
            });

        // Damage Groups

        var damageSortedGroups =
            damageable.DamagePerGroup.OrderByDescending(damage => damage.Value)
                .ToDictionary(x => x.Key, x => x.Value);

        IReadOnlyDictionary<string, FixedPoint2> damagePerType = damageable.Damage.DamageDict;

        DrawDiagnosticGroups(damageSortedGroups, damagePerType);

        SetMode(_mode);
    }

    private static string GetStatus(MobState mobState)
    {
        return mobState switch
        {
            MobState.Alive => Loc.GetString("health-analyzer-window-entity-alive-text"),
            MobState.Critical => Loc.GetString("health-analyzer-window-entity-critical-text"),
            MobState.Dead => Loc.GetString("health-analyzer-window-entity-dead-text"),
            _ => Loc.GetString("health-analyzer-window-entity-unknown-text"),
        };
    }

    private void DrawDiagnosticGroups(
        Dictionary<string, FixedPoint2> groups,
        IReadOnlyDictionary<string, FixedPoint2> damageDict)
    {
        GroupsContainer.RemoveAllChildren();

        foreach (var (damageGroupId, damageAmount) in groups)
        {
            if (damageAmount == 0)
                continue;

            var groupTitleText = $"{Loc.GetString(
                "health-analyzer-window-damage-group-text",
                ("damageGroup", _prototypes.Index<DamageGroupPrototype>(damageGroupId).LocalizedName),
                ("amount", damageAmount)
            )}";

            var groupContainer = new BoxContainer
            {
                Align = AlignMode.Begin,
                Orientation = LayoutOrientation.Vertical,
            };

            groupContainer.AddChild(CreateDiagnosticGroupTitle(groupTitleText, damageGroupId));

            GroupsContainer.AddChild(groupContainer);

            // Show the damage for each type in that group.
            var group = _prototypes.Index<DamageGroupPrototype>(damageGroupId);

            foreach (var type in group.DamageTypes)
            {
                if (!damageDict.TryGetValue(type, out var typeAmount) || typeAmount <= 0)
                    continue;

                var damageString = Loc.GetString(
                    "health-analyzer-window-damage-type-text",
                    ("damageType", _prototypes.Index<DamageTypePrototype>(type).LocalizedName),
                    ("amount", typeAmount)
                );

                groupContainer.AddChild(CreateDiagnosticItemLabel(damageString.Insert(0, " · ")));
            }
        }
    }

    private Texture GetTexture(string texture)
    {
        var rsiPath = new ResPath("/Textures/Objects/Devices/health_analyzer.rsi");
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);

        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
        if (!rsi.TryGetState(rsiSprite.RsiState, out var state))
        {
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");
        }

        return _spriteSystem.Frame0(rsiSprite);
    }

    private static Label CreateDiagnosticItemLabel(string text)
    {
        return new Label
        {
            Text = text,
        };
    }

    private BoxContainer CreateDiagnosticGroupTitle(string text, string id)
    {
        var rootContainer = new BoxContainer
        {
            Margin = new Thickness(0, 6, 0, 0),
            VerticalAlignment = VAlignment.Bottom,
            Orientation = LayoutOrientation.Horizontal,
        };

        rootContainer.AddChild(new TextureRect
        {
            SetSize = new Vector2(30, 30),
            Texture = GetTexture(id.ToLower())
        });

        rootContainer.AddChild(CreateDiagnosticItemLabel(text));

        return rootContainer;
    }
}
