using Content.Client.UserInterface.Controls;
using Content.Shared.Speech;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;


namespace Content.Client._DV.MenuPinpointer;
[GenerateTypedNameReferences]
public sealed partial class MenuPinpointerTargetWindow : FancyWindow
{
    public Action<string>? OnTargetSelect;
    public Action? OnToggleSelect;
    public MenuPinpointerTargetWindow()
    {
        RobustXamlLoader.Load(this);

        TargetSetButton.OnPressed += _ => { OnTargetSelect?.Invoke(TargetWriteZone.Text); };
        ToggleButton.OnPressed += _ => { OnToggleSelect?.Invoke(); };
    }
}
