using Content.Shared.Hands.Components;
using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Hotbar.Widgets;

[GenerateTypedNameReferences]
public sealed partial class HotbarGui : UIWidget
{
    /// <summary>
    /// When true, the leftmost hand button in the grid is the left hand (organic limbs).
    /// When false, the leftmost is the right hand (cyber limbs). Affects panel-to-hand mapping.
    /// </summary>
    private bool _leftmostHandIsLeft = true;

    public HotbarGui()
    {
        RobustXamlLoader.Load(this);
        // Panel positions: StatusPanelRight is left of hands, StatusPanelLeft is right.
        // Swap icons so they match the content shown in each position.
        StatusPanelRight.SetSide(HandLocation.Right);
        StatusPanelLeft.SetSide(HandLocation.Left);
        var hotbarController = UserInterfaceManager.GetUIController<HotbarUIController>();

        hotbarController.Setup(HandContainer);
        LayoutContainer.SetGrowVertical(this, LayoutContainer.GrowDirection.Begin);
    }

    /// <summary>
    /// Updates the hand-to-panel mapping based on the order of hands in the grid.
    /// Organic limbs typically have left hand first (leftmost); cyber limbs have right hand first.
    /// </summary>
    public void UpdateHandOrderMapping()
    {
        var firstButton = HandContainer.GetButtons().FirstOrDefault();
        _leftmostHandIsLeft = firstButton?.HandLocation == HandLocation.Left;
    }

    public void UpdatePanelEntityLeft(EntityUid? entity, Hand? hand)
    {
        // Panel positions: StatusPanelRight is left of hands, StatusPanelLeft is right (per ItemStatusPanel).
        // When leftmost hand is Right, use normal mapping. When Left, swap.
        if (_leftmostHandIsLeft)
            StatusPanelRight.Update(entity, hand);
        else
            StatusPanelLeft.Update(entity, hand);
    }

    public void UpdatePanelEntityRight(EntityUid? entity, Hand? hand)
    {
        if (_leftmostHandIsLeft)
            StatusPanelLeft.Update(entity, hand);
        else
            StatusPanelRight.Update(entity, hand);
    }

    public void SetHighlightHand(HandLocation? hand)
    {
        StatusPanelLeft.UpdateHighlight(hand is HandLocation.Left);
        StatusPanelRight.UpdateHighlight(hand is HandLocation.Right);
    }

    public void UpdateStatusVisibility(bool left, bool right)
    {
        // Match UpdatePanelEntity mapping: StatusPanelRight is on left, StatusPanelLeft on right.
        if (_leftmostHandIsLeft)
        {
            StatusPanelRight.Visible = left;
            StatusPanelLeft.Visible = right;
        }
        else
        {
            StatusPanelLeft.Visible = left;
            StatusPanelRight.Visible = right;
        }
    }
}
