- type: antag
  id: MalfunctioningAI
  name: roles-antag-malf-ai-name
  antagonist: true
  setPreference: true
  objective: roles-antag-malf-ai-objective
  guides: [ Traitors ] # this is temporary, if it's still Traitors by PR time please point that out
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h
  - !type:RoleTimeRequirement
    role: JobStationAi
    time: 10800 # 3h

- type: antag
  id: MalfunctioningCyborg
  name: roles-antag-malf-cyborg-name
  antagonist: true
  objective: roles-antag-malf-cyborg-objective