- type: antag
  id: Marauder
  name: roles-antag-marauder-name
  antagonist: true
  setPreference: true
  objective: roles-antag-marauder-objective
  guides: [ Traitors ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h
